/*
 * Copyright (C) 2020 Developer Guilliman <developerguilliman@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.developerguilliman.cardEditor.gui;

import com.developerguilliman.cardEditor.Utils;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
*
* @author Developer Guilliman <developerguilliman@gmail.com>
*/
public class AboutDialog extends javax.swing.JDialog {

    /**
     * Creates new form AboutDialog
     */
    public AboutDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        appNamePanel = new javax.swing.JPanel();
        appNameLabel = new javax.swing.JLabel();
        licensePanel = new javax.swing.JPanel();
        licenseLabel = new javax.swing.JLabel();
        poweredByPanel = new javax.swing.JPanel();
        poweredByLabel = new javax.swing.JLabel();
        wahapediaPanel = new javax.swing.JPanel();
        wahapediaLabel = new javax.swing.JLabel();
        wahapediaLinkLabel = new javax.swing.JLabel();
        jsoupPanel = new javax.swing.JPanel();
        jsoupLabel = new javax.swing.JLabel();
        jsoupLinkLabel = new javax.swing.JLabel();
        pdfboxPanel = new javax.swing.JPanel();
        pdfboxLabel = new javax.swing.JLabel();
        pdfboxLinkLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        appNamePanel.setLayout(new java.awt.GridLayout());

        appNameLabel.setBackground(new java.awt.Color(241, 241, 241));
        appNameLabel.setFont(appNameLabel.getFont().deriveFont(appNameLabel.getFont().getStyle() | java.awt.Font.BOLD, appNameLabel.getFont().getSize()+9));
        appNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appNameLabel.setText(Utils.getApplicationName()
        );
        appNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        appNameLabel.setMaximumSize(new java.awt.Dimension(32767, 21));
        appNameLabel.setMinimumSize(new java.awt.Dimension(250, 32));
        appNamePanel.add(appNameLabel);

        getContentPane().add(appNamePanel);

        licensePanel.setLayout(new java.awt.GridLayout());

        licenseLabel.setText("<html> Copyright (C) 2020 Developer Guilliman developerguilliman@gmail.com <br/>This program is licensed under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. </html>");
        licenseLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        licensePanel.add(licenseLabel);

        getContentPane().add(licensePanel);

        poweredByPanel.setLayout(new java.awt.GridLayout(0, 1));

        poweredByLabel.setText("<html>Powered by:</html>");
        poweredByLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        poweredByPanel.add(poweredByLabel);

        wahapediaPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        wahapediaLabel.setText("Online card importing using");
        wahapediaLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        wahapediaPanel.add(wahapediaLabel);

        wahapediaLinkLabel.setText("<html><a href=\"https://wahapedia.ru/\">Wahapedia</a></html>");
        wahapediaLinkLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        wahapediaLinkLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wahapediaLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wahapediaLinkLabelMouseClicked(evt);
            }
        });
        wahapediaPanel.add(wahapediaLinkLabel);

        poweredByPanel.add(wahapediaPanel);

        jsoupPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jsoupLabel.setText("HTML querying using");
        jsoupLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsoupPanel.add(jsoupLabel);

        jsoupLinkLabel.setText("<html><a href=\"https://jsoup.org/\">jsoup</a></html>");
        jsoupLinkLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jsoupLinkLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsoupLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jsoupLinkLabelMouseClicked(evt);
            }
        });
        jsoupPanel.add(jsoupLinkLabel);

        poweredByPanel.add(jsoupPanel);

        pdfboxPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        pdfboxLabel.setText("PDF generated using");
        pdfboxLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pdfboxPanel.add(pdfboxLabel);

        pdfboxLinkLabel.setText("<html><a href=\"https://pdfbox.apache.org/\">Apache PDFBox</a></html>");
        pdfboxLinkLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pdfboxLinkLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pdfboxLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdfboxLinkLabelMouseClicked(evt);
            }
        });
        pdfboxPanel.add(pdfboxLinkLabel);

        poweredByPanel.add(pdfboxPanel);

        getContentPane().add(poweredByPanel);

        setBounds(0, 0, 673, 274);
    }// </editor-fold>//GEN-END:initComponents

    private void wahapediaLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wahapediaLinkLabelMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://wahapedia.ru/"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_wahapediaLinkLabelMouseClicked

    private void jsoupLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsoupLinkLabelMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://jsoup.org/"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jsoupLinkLabelMouseClicked

    private void pdfboxLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdfboxLinkLabelMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://pdfbox.apache.org/"));
        } catch (IOException | URISyntaxException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_pdfboxLinkLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JPanel appNamePanel;
    private javax.swing.JLabel jsoupLabel;
    private javax.swing.JLabel jsoupLinkLabel;
    private javax.swing.JPanel jsoupPanel;
    private javax.swing.JLabel licenseLabel;
    private javax.swing.JPanel licensePanel;
    private javax.swing.JLabel pdfboxLabel;
    private javax.swing.JLabel pdfboxLinkLabel;
    private javax.swing.JPanel pdfboxPanel;
    private javax.swing.JLabel poweredByLabel;
    private javax.swing.JPanel poweredByPanel;
    private javax.swing.JLabel wahapediaLabel;
    private javax.swing.JLabel wahapediaLinkLabel;
    private javax.swing.JPanel wahapediaPanel;
    // End of variables declaration//GEN-END:variables
}
